version: '3'

services:
  merchant-db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - merchant-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 10s
      retries: 3

  atlas-migrations:
    image: "arigaio/atlas:latest"
    volumes:
      - ./migrations:/migrations
    depends_on:
      merchant-db:
        condition: "service_healthy"
    command: migrate apply --dir file://migrations --url postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@merchant-db:5432/${POSTGRES_DB}?sslmode=disable

volumes:
  merchant-data: